name: datahub_codegen
description: DataHub Code Generation Lib
version: 0.1.0
homepage: https://datahubproject.net

environment:
  sdk: '>=2.17.1 <3.0.0'

dependencies:
   datahub: 0.12.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
