name: datahub_codegen
description: DataHub Code Generation Lib
version: 0.15.0
homepage: https://datahubproject.net

environment:
  sdk: '>=2.17.1 <3.0.0'

dependencies:
   analyzer: ^4.2.0
   boost: ^1.7.0
   build: ^2.3.0
   datahub: '>=0.15.0-dev.1 <0.16.0'
   source_gen: ^1.2.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
