name: datahub_codegen
description: DataHub Code Generation Lib
version: 0.17.0-dev.19
homepage: https://datahubproject.net
repository: https://github.com/christian-thiele/datahub_codegen

environment:
  sdk: ^3.1.0

dependencies:
  analyzer: ^5.13.0
  boost: ^1.8.10
  build: ^2.3.0
  datahub: '>=0.17.0-dev.62 <1.0.0'
  source_gen: ^1.2.7

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.6
  build_runner: ^2.4.0
