name: datahub_codegen
description: DataHub Code Generation Lib
version: 0.17.0-dev.10
homepage: https://datahubproject.net

environment:
  sdk: '>=2.17.1 <4.0.0'

dependencies:
   analyzer: ^6.1.0
   boost: ^1.8.7
   build: ^2.3.0
   datahub: '>=0.17.0-dev.19 <1.0.0'
   source_gen: ^1.2.7

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.6
  build_runner: ^2.4.0
